---
layout:     post
title: "Customer Analytics"
date:       2020-02-25 11:21:29
summary:    Customers Data segmentation using PCA and K-means.
output: rmarkdown::github_document
---
###Customers Data segmentation using PCA and K-means

This is a quick project where I'll demonstrate the correct way to segment customers data
for further analysis. The purpose of customers analytics is to provide new usefull insights.The necessary columns for any customers analysis are the customers personal informations -which can be surveyed through different method such as loyality subscriptions- and a detailed purchase history for each customer. I'll be using python for this analysis, let's start.


```{r setup, include=FALSE}
library(reticulate)
use_condaenv('C:\\Users\\Fayez\\AppData\\Local\\R-MINI~1\\envs\\r-reticulate\\')

```






#### Here I will load the necessary packages and import the dataset


```{python}

import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
full = pd.read_csv('dataset.csv')
print(full.head())
print(full.columns)
df = full[['Sex', 'Marital status', 'Age', 'Education', 'Income','Occupation', 'Settlement size']]

```

#### This is the customers informations data set that contains basic informations... We'll plot the correlations between each column using a Heat Map. Heat Maps are a great way to visualize correlations using color coding.

```{python,fig.align='center',out.extra='angle=90',echo=FALSE}
s = sns.heatmap(df.corr(),
               annot = True, 
               cmap = 'RdBu',
               vmin = -1, 
               vmax = 1)
s.set_yticklabels(s.get_yticklabels(), rotation = 30, fontsize = 10)

s.set_xticklabels(s.get_xticklabels(), rotation = 90, fontsize = 12)

plt.title('Correlation Heatmap')

plt.show()
```
This heatmap shows basic correlations informations:
1. Age and Education are positively correlated
2. Occupation and income are correlated
3.Women are slightly more educated then men

... non of these can be considered as an insight... it can be deducted based on intuition.

yet it's good to know that our data is based on real observations


### Visualizing Raw Data
We have 2000 data points, which we'll scatter acrros Age and Income.
```{python}
plt.figure(figsize = (12, 9))
plt.scatter(df.iloc[:, 2], df.iloc[:, 4])
plt.xlabel('Age')
plt.ylabel('Income')
plt.title('Visualization of raw data')
```


###Standardization
Standardizing data, so that all features have equal weight. This is important for modelling. Otherwise, in our case Income would be considered much more important than Education for Instance. 

```{python}
scaler = StandardScaler()
df_std = scaler.fit_transform(df)
```

### Hierarchical Clustering
```{python}
hier_clust = linkage(df_std, method = 'ward')
plt.figure(figsize = (12,9))
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Observations')
plt.ylabel('Distance')
dendrogram(hier_clust,
           truncate_mode = 'level', 
           p = 5, 
           show_leaf_counts = False, 
           no_labels = True)
plt.show()
```

### K-means Clustering with PCA

```{python}
pca = PCA()
pca.fit(df_std)
plt.figure(figsize = (12,9))
plt.plot(range(1,8), pca.explained_variance_ratio_.cumsum(), marker = 'o', linestyle = '--')
plt.title('Explained Variance by Components')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.show()
```

Generally, we want to keep around 80-90% of the explained variance, here I chose 3 components

```{python}
pca = PCA(n_components = 3)
pca.fit(df_std)

df_pca_comp = pd.DataFrame(data = pca.components_,
                           columns = df.columns.values,
                           index = ['Component 1', 'Component 2', 'Component 3'])
df_pca_comp


```


### Heat Map for Principal Components against original features
```{python}

sns.heatmap(df_pca_comp,
            vmin = -1, 
            vmax = 1,
            cmap = 'RdBu',
            annot = True)
plt.yticks([0, 1, 2], 
           ['Component 1', 'Component 2', 'Component 3'],
           rotation = 45,
           fontsize = 9)
plt.show()
```



###Applying our PCA model to the dataset and choosing the correct number of kmean clusters

There are many methods for choosing the number of clusters, the quickest one is the "Elbow Methode".


```{python}


pca.transform(df_std)
scores_pca = pca.transform(df_std)

wcss = []
for i in range(1,11):
    kmeans_pca = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans_pca.fit(scores_pca)
    wcss.append(kmeans_pca.inertia_)
    
plt.figure(figsize = (10,8))
plt.plot(range(1, 11), wcss, marker = 'o', linestyle = '--')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('K-means with PCA Clustering')
plt.show()
```
4 clusters seems to be the right number to choose

```{python}
kmeans_pca = KMeans(n_clusters = 4, init = 'k-means++', random_state = 42)
kmeans_pca.fit(scores_pca)

df_segm_pca_kmeans = pd.concat([df.reset_index(drop = True), pd.DataFrame(scores_pca)], axis = 1)
df_segm_pca_kmeans.columns.values[-3: ] = ['Component 1', 'Component 2', 'Component 3']
```
The last column we add contains the pca k-means clustering labels.

```{python}
df_segm_pca_kmeans['Segment K-means PCA'] = kmeans_pca.labels_

df_segm_pca_kmeans

df_segm_pca_kmeans_freq = df_segm_pca_kmeans.groupby(['Segment K-means PCA']).mean()
df_segm_pca_kmeans_freq

df_segm_pca_kmeans_freq['N Obs'] = df_segm_pca_kmeans[['Segment K-means PCA','Sex']].groupby(['Segment K-means PCA']).count()
df_segm_pca_kmeans_freq['Prop Obs'] = df_segm_pca_kmeans_freq['N Obs'] / df_segm_pca_kmeans_freq['N Obs'].sum()
```
Cluster 0 seems to be mostly married females with middle range income and with basic education and age arround 28,
we will call this cluster millenials.

Cluster 1 is mostly single middle aged men with low education and high income, we will call it Gentles.

Cluster 2 mostly single middle aged men with low education and low income,
we will call it Unlucky.

Finally Cluster 3 mostly High educated with the highest income with age around 55, we will call it seniors,




```{python}
df_segm_pca_kmeans_freq = df_segm_pca_kmeans_freq.rename({0:'Mellineals', 
                                                          1:'Gentles',
                                                          2:'Unlucky', 
                                                          3:'Seniors'})
df_segm_pca_kmeans_freq

df_segm_pca_kmeans['Legend'] = df_segm_pca_kmeans['Segment K-means PCA'].map({0:'Nellineals', 
                                                          1:'Gentles',
                                                          2:'Unlucky', 
                                                          3:'Seniors'})
                                                          
x_axis = df_segm_pca_kmeans['Component 2']
y_axis = df_segm_pca_kmeans['Component 1']
plt.figure(figsize = (10, 8))
sns.scatterplot(x_axis, y_axis, hue = df_segm_pca_kmeans['Legend'], palette = ['g', 'r', 'c', 'm'])
plt.title('Clusters by PCA Components')
plt.show()
```



##Final note

The final clustered data set can be further analysed with descriptive statisticals methods, but I will stop here. I hope this mini project was informative and showed the correct way in clustering customers data.


###Fayez Alshehri